package model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.apache.commons.lang3.EnumUtils;

import java.util.Date;
@DynamoDBTable(tableName = "Incidencia")
public class Incidencia {
    private Date date;
    private String origin;
    private String destination;
    private String detail;
    private String type;
    private String id;

    @DynamoDBAttribute(attributeName = "Date")
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @DynamoDBAttribute(attributeName = "Origin")
    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    @DynamoDBAttribute(attributeName = "Destination")
    public String getDestination() {
        return destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    @DynamoDBAttribute(attributeName = "Detail")
    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    @DynamoDBAttribute(attributeName = "Type")
    public String getType() {
        return type;
    }

    public void setType( String type) {
        if (EnumUtils.isValidEnum(TipoUrgencia.class, type.toUpperCase()))
            this.type = type;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey()
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
